In [1]:
import pandas as pd

df = pd.read_csv("youtube_dataset.csv")

df.head()

C:\Users\shadi\AppData\Local\Temp\ipykernel_9476\3725381955.py:3: DtypeWarning: Columns (14,15,45,46,47,48,52,55,56,57,58,59,60,61,65,66) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("youtube_dataset.csv")

,video_id,channel_name,category,channel_id,viewCount,likeCount,commentCount,title,description,tags,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
0,NiSgmQ2ILoI,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,26155.0,548.0,4.0,호박이 음료로 변신?! 수작업과 현대기술이 만난 전통 식혜공장,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8A2ForFWLpM,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,20362.0,595.0,10.0,소고기 좋아하죠?! 입 벌어지는 초스피드 한우 발골 공장,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,aNoAUON6fsU,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,66588.0,1531.0,15.0,독일 소시지 대회 6관왕! 떡갈비맛 소시지 대량생산,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,gekD8gOgQgQ,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,138222.0,4109.0,23.0,초코퐁당! 의외로 수작업 많은 수제 초코파이 대량생산,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,VcW4Wwnr25Y,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,53033.0,999.0,6.0,이렇게 만듭니다! 1분순삭 코코넛 치킨링 대량생산,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70826 entries, 0 to 70825
Data columns (total 67 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                70826 non-null  object
 1   channel_name            70826 non-null  object
 2   category                70826 non-null  object
 3   channel_id              70826 non-null  object
 4   viewCount               70737 non-null  float64
 5   likeCount               67035 non-null  float64
 6   commentCount            69949 non-null  float64
 7   title                   70826 non-null  object
 8   description             0 non-null      float64
 9   tags                    0 non-null      float64
 10  publishedAt             70826 non-null  object
 11  duration                70730 non-null  object
 12  dimension               70737 non-null  object
 13  definition              70737 non-null  object
 14  caption                 70737 non-null  object
 15  licensedContent         70737 non-null  object
 16  projection              70737 non-null  object
 17  liveActualStartTime     0 non-null      float64
 18  liveScheduledStartTime  0 non-null      float64
 19  concurrentViewers       70 non-null     float64
 20  snapshot_date           70826 non-null  object
 21  thumbnail_file          70826 non-null  object
 22  Unnamed: 22             0 non-null      float64
 23  Unnamed: 23             0 non-null      float64
 24  Unnamed: 24             0 non-null      float64
 25  Unnamed: 25             0 non-null      float64
 26  Unnamed: 26             0 non-null      float64
 27  Unnamed: 27             0 non-null      float64
 28  Unnamed: 28             0 non-null      float64
 29  Unnamed: 29             0 non-null      float64
 30  Unnamed: 30             0 non-null      float64
 31  Unnamed: 31             0 non-null      float64
 32  Unnamed: 32             0 non-null      float64
 33  Unnamed: 33             0 non-null      float64
 34  Unnamed: 34             0 non-null      float64
 35  Unnamed: 35             0 non-null      float64
 36  Unnamed: 36             0 non-null      float64
 37  Unnamed: 37             0 non-null      float64
 38  Unnamed: 38             0 non-null      float64
 39  Unnamed: 39             0 non-null      float64
 40  Unnamed: 40             0 non-null      float64
 41  Unnamed: 41             0 non-null      float64
 42  Unnamed: 42             0 non-null      float64
 43  Unnamed: 43             0 non-null      float64
 44  Unnamed: 44             0 non-null      float64
 45  Unnamed: 45             1 non-null      object
 46  Unnamed: 46             1 non-null      object
 47  Unnamed: 47             1 non-null      object
 48  Unnamed: 48             1 non-null      object
 49  Unnamed: 49             1 non-null      float64
 50  Unnamed: 50             1 non-null      float64
 51  Unnamed: 51             1 non-null      float64
 52  Unnamed: 52             1 non-null      object
 53  Unnamed: 53             0 non-null      float64
 54  Unnamed: 54             0 non-null      float64
 55  Unnamed: 55             1 non-null      object
 56  Unnamed: 56             1 non-null      object
 57  Unnamed: 57             1 non-null      object
 58  Unnamed: 58             1 non-null      object
 59  Unnamed: 59             1 non-null      object
 60  Unnamed: 60             1 non-null      object
 61  Unnamed: 61             1 non-null      object
 62  Unnamed: 62             0 non-null      float64
 63  Unnamed: 63             0 non-null      float64
 64  Unnamed: 64             0 non-null      float64
 65  Unnamed: 65             1 non-null      object
 66  Unnamed: 66             1 non-null      object
dtypes: float64(39), object(28)
memory usage: 36.2+ MB

,viewCount,likeCount,commentCount,description,tags,liveActualStartTime,liveScheduledStartTime,concurrentViewers,Unnamed: 22,Unnamed: 23,...,Unnamed: 43,Unnamed: 44,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 53,Unnamed: 54,Unnamed: 62,Unnamed: 63,Unnamed: 64
count,7.073700e+04,6.703500e+04,6.994900e+04,0.0,0.0,0.0,0.0,70.000000,0.0,0.0,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
mean,1.190909e+06,2.001274e+04,5.209622e+02,NaN,NaN,NaN,NaN,138.785714,NaN,NaN,...,NaN,NaN,2634.0,98.0,3.0,NaN,NaN,NaN,NaN,NaN
std,1.299997e+07,1.214238e+05,8.203984e+03,NaN,NaN,NaN,NaN,243.020658,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,...,NaN,NaN,2634.0,98.0,3.0,NaN,NaN,NaN,NaN,NaN
25%,1.364000e+04,2.160000e+02,3.000000e+00,NaN,NaN,NaN,NaN,10.500000,NaN,NaN,...,NaN,NaN,2634.0,98.0,3.0,NaN,NaN,NaN,NaN,NaN
50%,5.613800e+04,1.335000e+03,3.000000e+01,NaN,NaN,NaN,NaN,37.500000,NaN,NaN,...,NaN,NaN,2634.0,98.0,3.0,NaN,NaN,NaN,NaN,NaN
75%,3.053670e+05,8.188000e+03,1.940000e+02,NaN,NaN,NaN,NaN,125.000000,NaN,NaN,...,NaN,NaN,2634.0,98.0,3.0,NaN,NaN,NaN,NaN,NaN
max,1.022044e+09,1.021578e+07,1.880322e+06,NaN,NaN,NaN,NaN,1301.000000,NaN,NaN,...,NaN,NaN,2634.0,98.0,3.0,NaN,NaN,NaN,NaN,NaN

In [49]:
#Merge columns in channel_list.csv with youtube_dataset.csv to get all of the required features for the model
import pandas as pd
import numpy as np

import re

#Load youstube_dataset and drop all Unnamed columns
youtube_videos= pd.read_csv("youtube_dataset.csv", low_memory=False)
youtube_videos = youtube_videos.loc[:, ~youtube_videos.columns.str.contains('^Unnamed')]

#Load channel_list.csv 
youtube_channels = pd.read_csv("channel_list.csv", engine = "python", encoding="utf-8", on_bad_lines="skip")

#Extract only the columns needed from channel_list.csv
columns_needed = ["channel_id", "channel_subscriberCount", "channel_viewCount", "channel_videoCount"]

#List comprehension ensures only one row for every channel and drops all duplicates
youtube_channels = youtube_channels[[column for column in columns_needed if column in youtube_channels.columns]].drop_duplicates("channel_id")

df = youtube_videos.merge(youtube_channels, on="channel_id", how="left") #Merge both datasets by channel id
df.head()

,video_id,channel_name,category,channel_id,viewCount,likeCount,commentCount,title,description,tags,...,licensedContent,projection,liveActualStartTime,liveScheduledStartTime,concurrentViewers,snapshot_date,thumbnail_file,channel_subscriberCount,channel_viewCount,channel_videoCount
0,NiSgmQ2ILoI,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,26155.0,548.0,4.0,호박이 음료로 변신?! 수작업과 현대기술이 만난 전통 식혜공장,NaN,NaN,...,True,rectangular,NaN,NaN,NaN,2025-10-13T17:05:58.087262+00:00,NiSgmQ2ILoI.jpg,5250000.0,2.873756e+09,1845.0
1,8A2ForFWLpM,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,20362.0,595.0,10.0,소고기 좋아하죠?! 입 벌어지는 초스피드 한우 발골 공장,NaN,NaN,...,True,rectangular,NaN,NaN,NaN,2025-10-13T17:05:58.271605+00:00,8A2ForFWLpM.jpg,5250000.0,2.873756e+09,1845.0
2,aNoAUON6fsU,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,66588.0,1531.0,15.0,독일 소시지 대회 6관왕! 떡갈비맛 소시지 대량생산,NaN,NaN,...,True,rectangular,NaN,NaN,NaN,2025-10-13T17:05:58.442200+00:00,aNoAUON6fsU.jpg,5250000.0,2.873756e+09,1845.0
3,gekD8gOgQgQ,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,138222.0,4109.0,23.0,초코퐁당! 의외로 수작업 많은 수제 초코파이 대량생산,NaN,NaN,...,True,rectangular,NaN,NaN,NaN,2025-10-13T17:05:58.620646+00:00,gekD8gOgQgQ.jpg,5250000.0,2.873756e+09,1845.0
4,VcW4Wwnr25Y,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,53033.0,999.0,6.0,이렇게 만듭니다! 1분순삭 코코넛 치킨링 대량생산,NaN,NaN,...,True,rectangular,NaN,NaN,NaN,2025-10-13T17:05:58.801464+00:00,VcW4Wwnr25Y.jpg,5250000.0,2.873756e+09,1845.0

In [12]:
df[["channel_id","channel_subscriberCount", "channel_viewCount", "channel_videoCount"]].head()

,channel_id,channel_subscriberCount,channel_viewCount,channel_videoCount
0,UC4BfinFCS1o6t1tAsl0RVWQ,5250000.0,2.873756e+09,1845.0
1,UC4BfinFCS1o6t1tAsl0RVWQ,5250000.0,2.873756e+09,1845.0
2,UC4BfinFCS1o6t1tAsl0RVWQ,5250000.0,2.873756e+09,1845.0
3,UC4BfinFCS1o6t1tAsl0RVWQ,5250000.0,2.873756e+09,1845.0
4,UC4BfinFCS1o6t1tAsl0RVWQ,5250000.0,2.873756e+09,1845.0

In [13]:
df.columns[-10:]

Index(['licensedContent', 'projection', 'liveActualStartTime',
       'liveScheduledStartTime', 'concurrentViewers', 'snapshot_date',
       'thumbnail_file', 'channel_subscriberCount', 'channel_viewCount',
       'channel_videoCount'],
      dtype='object')

In [14]:
df.columns.tolist()

['video_id',
 'channel_name',
 'category',
 'channel_id',
 'viewCount',
 'likeCount',
 'commentCount',
 'title',
 'description',
 'tags',
 'publishedAt',
 'duration',
 'dimension',
 'definition',
 'caption',
 'licensedContent',
 'projection',
 'liveActualStartTime',
 'liveScheduledStartTime',
 'concurrentViewers',
 'snapshot_date',
 'thumbnail_file',
 'channel_subscriberCount',
 'channel_viewCount',
 'channel_videoCount']

In [47]:
#Convert all of the required columns into numerical values

df = df.loc[:, ~df.columns.str.contains(r'^Unnamed', case=False, na=False)].copy() #Remove unwanted columns

#Regular expression to detect Youtube API style video durations in the form of a string "PT6M22S" -> 6 minutes, 22 seconds
duration = re.compile(r"^P(?:\d+Y)?(?:\d+M)?(?:\d+D)?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?)?$") 

#Function to convert ISO8601 duration strings (format of Youtube API duration) into seconds
def convert_to_seconds(t):
    if not isinstance(t,str):  #If the duration, t is not a string return NaN
        return np.nan 
    minutes=duration.match(t) #Matches t with the regular expression, 'duration' created above
    if not minutes: 
        return np.nan   #If t does not match duration return NaN
    hrs, mins, sec = minutes.groups() #If t matches duration convert the duration string into hours, minutes and seconds
    hrs = int(hrs) if hrs else 0
    mins = int(mins) if mins else 0
    sec = int(sec) if sec else 0
    return 3600*hrs + 60*mins + sec

#Adds a new column for the video length and calls the function to convert the ISO8601 string into seconds 
if "duration" in df.columns: 
    df["video_length"] = df["duration"].apply(convert_to_seconds) 

#If a timestamp exists in the publishedAt column of the df convert the string timestamp into datetime pandas objects
if "publishedAt" in df.columns:
    df["publish_date"] = pd.to_datetime(df["publishedAt"], errors = "coerce") 

#If there is a column containing a snapshot of the date the data was collected convert to datetime format
if "snapshot_date" in df.columns:
    df["snapshot_dt"] = pd.to_datetime(df["snapshot_date"], errors="coerce")
    
    reference_date_time = df["snapshot_dt"] # Use this datetime format as a reference date
else:
    reference_date_time = pd.Timestamp.utcnow() #If there is no snapshot date use today's date

#Subtracts the publish time datetime object from the reference datetime object to obtain a Timedelta object in the form X days HH:MM:SS.mmmmmm    
if "publish_date" in df.columns:
    df["video_age"] = (reference_date_time - df["publish_date"]).dt.days #Extracts the number of days, X from the Timedelta object

#Defines all the columns in the dataframe that should be numeric
columns_to_numeric = ["likeCount", "viewCount", "channel_subscriberCount", "commentCount", "channel_viewCount", 
                      "video_length", "channel_videoCount", "video_age"]

#Converts each of those columns into numerical values
for column in columns_to_numeric:
    if column in df.columns:
        df[column] = pd.to_numeric(df[column], errors = "coerce")

category_columns = [] #Empty list used to store category columns

#If the dataset contains a category column consisting of text convert it into dummy binary columns. 1 if belongs to category and 0 if not
if "category" in df.columns: 
    if df["category"].dtype == "O":
        df=pd.get_dummies(df, columns=["category"],prefix="cat", dummy_na=True)
        category_columns = [column for column in df.columns if column.startswith("cat_")]

    #If category column is already numeric store it and handle invalid values
    else:
        df["category"] = pd.to_numeric(df["category"], errors="coerce")
        
#Feature matrix containing all features that will be used in model training

matrix_features = ["viewCount","likeCount", "video_age", "video_length", "channel_subscriberCount", "channel_viewCount",
                   "commentCount", "channel_videoCount", ]

matrix_features += category_columns #Add category columns to the feature matrix

matrix_X = df[matrix_features].fillna(0) #New dataframe which only contains the columns in feature matrix

print(f"Rows: {len(matrix_X):,}") 
print(f"No of features: {len(matrix_features)}") 
print("Columns: ", matrix_features[:5])

matrix_X.head()

Rows: 70,826
No of features: 8
Columns:  ['viewCount', 'likeCount', 'video_age', 'video_length', 'channel_subscriberCount']

,viewCount,likeCount,video_age,video_length,channel_subscriberCount,channel_viewCount,commentCount,channel_videoCount
0,26155.0,548.0,0,60.0,5250000.0,2.873756e+09,4.0,1845.0
1,20362.0,595.0,1,61.0,5250000.0,2.873756e+09,10.0,1845.0
2,66588.0,1531.0,2,61.0,5250000.0,2.873756e+09,15.0,1845.0
3,138222.0,4109.0,4,60.0,5250000.0,2.873756e+09,23.0,1845.0
4,53033.0,999.0,4,60.0,5250000.0,2.873756e+09,6.0,1845.0

In [21]:
df["channel_id"].nunique()

390

In [22]:
df[["channel_id","channel_name"]].drop_duplicates().head(10)

                    channel_id          channel_name
0     UC4BfinFCS1o6t1tAsl0RVWQ     푸드킹덤 Food Kingdom
102   UCdz7HcTQOaHCoAEJBs-MlNQ         찐푸드 JJin Food
268   UCfyehHM_eo4g5JUyWmms2LA           Sorted Food
371   UCl0kP-Cfe-GGic7Ilnk-u_Q         Everyday Food
571   UCbgYZnybgb6vPSBTxZUT2kA      Veg Village Food
732   UCuqBZWK9Wrol_4Y22DzisFQ           Food Fusion
834   UCdupQvA3NlGfyaPaZKWSgTA   Meghna's Food Magic
952   UCRIZtPl9nb9RiXc9btSTQNw           Food Wishes
1089  UC-j7LP4at37y3uNTdWLq-vQ  Village food factory
1287  UCncnlpiTnf89IJrekMKoa3A          Food on Farm

In [23]:
df[["channel_id","channel_name"]].drop_duplicates().head(390)

                     channel_id        channel_name
0      UC4BfinFCS1o6t1tAsl0RVWQ   푸드킹덤 Food Kingdom
102    UCdz7HcTQOaHCoAEJBs-MlNQ       찐푸드 JJin Food
268    UCfyehHM_eo4g5JUyWmms2LA         Sorted Food
371    UCl0kP-Cfe-GGic7Ilnk-u_Q       Everyday Food
571    UCbgYZnybgb6vPSBTxZUT2kA    Veg Village Food
...                         ...                 ...
69826  UC8yODbj0cUR6PPMtlLO82vw        Madness 24×7
70026  UCd84R_z_9WSEcRRXGDlRgMA  Rajesh kadam vlogs
70226  UCUB8SHTYP3QtlA-Ufju7AfQ     Abeda Ezy Craft
70426  UCx1TZomHnj41xVTLC4IWXSw  Saurabh Experiment
70626  UCZ6kmTdQa549fEGN-4reFfg         Craft Ideas

[390 rows x 2 columns]

In [29]:
df["predicted_views"] = df["viewCount"] * np.random.uniform(1.1,1.5,len(df))

In [32]:
df[["viewCount", "predicted_views"]].head()

   viewCount  predicted_views
0    26155.0     36506.590695
1    20362.0     22484.894802
2    66588.0     90032.782509
3   138222.0    176379.378028
4    53033.0     62163.770481

In [33]:
X = df[matrix_features].fillna(0)
y = ["predicted_views"]

In [69]:
print(df.columns)

Index(['video_id', 'channel_name', 'category', 'channel_id', 'viewCount',
       'likeCount', 'commentCount', 'title', 'description', 'tags',
       'publishedAt', 'duration', 'dimension', 'definition', 'caption',
       'licensedContent', 'projection', 'liveActualStartTime',
       'liveScheduledStartTime', 'concurrentViewers', 'snapshot_date',
       'thumbnail_file', 'channel_subscriberCount', 'channel_viewCount',
       'channel_videoCount'],
      dtype='object')

In [71]:
# 1) Sanity checks
print("'video_age' present:", 'video_age' in df.columns)
print("video_age dtype:", df['video_age'].dtype)
print("NaNs in video_age:", df['video_age'].isna().sum())
print("Min/Max video_age:", df['video_age'].min(), df['video_age'].max())
print(df[['publishedAt','snapshot_date','publish_date','video_age']].head())

'video_age' present: False

KeyError: 'video_age'