In [4]:
import pandas as pd

yt = pd.read_csv("data/raw/youtube_dataset.csv")
yt.shape

C:\Users\yashv\AppData\Local\Temp\ipykernel_14688\1917648542.py:3: DtypeWarning: Columns (14,15,45,46,47,48,52,55,56,57,58,59,60,61,65,66) have mixed types. Specify dtype option on import or set low_memory=False.
  yt = pd.read_csv("data/raw/youtube_dataset.csv")

(70826, 67)

In [23]:
yt.head(5)

,video_id,channel_name,category,channel_id,viewCount,likeCount,commentCount,title,description,tags,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
0,NiSgmQ2ILoI,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,26155.0,548.0,4.0,호박이 음료로 변신?! 수작업과 현대기술이 만난 전통 식혜공장,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8A2ForFWLpM,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,20362.0,595.0,10.0,소고기 좋아하죠?! 입 벌어지는 초스피드 한우 발골 공장,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,aNoAUON6fsU,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,66588.0,1531.0,15.0,독일 소시지 대회 6관왕! 떡갈비맛 소시지 대량생산,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,gekD8gOgQgQ,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,138222.0,4109.0,23.0,초코퐁당! 의외로 수작업 많은 수제 초코파이 대량생산,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,VcW4Wwnr25Y,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,53033.0,999.0,6.0,이렇게 만듭니다! 1분순삭 코코넛 치킨링 대량생산,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
yt.description

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
70821   NaN
70822   NaN
70823   NaN
70824   NaN
70825   NaN
Name: description, Length: 70826, dtype: float64

In [9]:
yt.columns

Index(['video_id', 'channel_name', 'category', 'channel_id', 'viewCount',
       'likeCount', 'commentCount', 'title', 'description', 'tags',
       'publishedAt', 'duration', 'dimension', 'definition', 'caption',
       'licensedContent', 'projection', 'liveActualStartTime',
       'liveScheduledStartTime', 'concurrentViewers', 'snapshot_date',
       'thumbnail_file', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28',
       'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32',
       'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36',
       'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40',
       'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44',
       'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48',
       'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52',
       'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56',
       'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60',
       'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64',
       'Unnamed: 65', 'Unnamed: 66'],
      dtype='object')

In [10]:
yt_drop = yt.iloc[:, :21]

In [14]:
yt_drop.columns

Index(['video_id', 'channel_name', 'category', 'channel_id', 'viewCount',
       'likeCount', 'commentCount', 'title', 'description', 'tags',
       'publishedAt', 'duration', 'dimension', 'definition', 'caption',
       'licensedContent', 'projection', 'liveActualStartTime',
       'liveScheduledStartTime', 'concurrentViewers', 'snapshot_date'],
      dtype='object')

In [18]:
#Removed all empty columns 
yt_drop.to_csv("youtube_dataset2.csv", index =False)

In [21]:
#Calling new dataset without all empty columns
yt2 = pd.read_csv("youtube_dataset2.csv")
yt2.head()

C:\Users\yashv\AppData\Local\Temp\ipykernel_14688\669366822.py:2: DtypeWarning: Columns (14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  yt2 = pd.read_csv("youtube_dataset2.csv")

,video_id,channel_name,category,channel_id,viewCount,likeCount,commentCount,title,description,tags,...,duration,dimension,definition,caption,licensedContent,projection,liveActualStartTime,liveScheduledStartTime,concurrentViewers,snapshot_date
0,NiSgmQ2ILoI,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,26155.0,548.0,4.0,호박이 음료로 변신?! 수작업과 현대기술이 만난 전통 식혜공장,NaN,NaN,...,PT1M,2d,hd,False,True,rectangular,NaN,NaN,NaN,2025-10-13T17:05:58.087262+00:00
1,8A2ForFWLpM,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,20362.0,595.0,10.0,소고기 좋아하죠?! 입 벌어지는 초스피드 한우 발골 공장,NaN,NaN,...,PT1M1S,2d,hd,False,True,rectangular,NaN,NaN,NaN,2025-10-13T17:05:58.271605+00:00
2,aNoAUON6fsU,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,66588.0,1531.0,15.0,독일 소시지 대회 6관왕! 떡갈비맛 소시지 대량생산,NaN,NaN,...,PT1M1S,2d,hd,False,True,rectangular,NaN,NaN,NaN,2025-10-13T17:05:58.442200+00:00
3,gekD8gOgQgQ,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,138222.0,4109.0,23.0,초코퐁당! 의외로 수작업 많은 수제 초코파이 대량생산,NaN,NaN,...,PT1M,2d,hd,False,True,rectangular,NaN,NaN,NaN,2025-10-13T17:05:58.620646+00:00
4,VcW4Wwnr25Y,푸드킹덤 Food Kingdom,Food,UC4BfinFCS1o6t1tAsl0RVWQ,53033.0,999.0,6.0,이렇게 만듭니다! 1분순삭 코코넛 치킨링 대량생산,NaN,NaN,...,PT1M,2d,hd,False,True,rectangular,NaN,NaN,NaN,2025-10-13T17:05:58.801464+00:00

In [25]:
#Checking the % of columns which are empty for removal
missing_percentages = yt2.isnull().sum() * 100 / len(yt2)
missing_percentages

video_id                    0.000000
channel_name                0.000000
category                    0.000000
channel_id                  0.000000
viewCount                   0.125660
likeCount                   5.352554
commentCount                1.238246
title                       0.000000
description               100.000000
tags                      100.000000
publishedAt                 0.000000
duration                    0.135543
dimension                   0.125660
definition                  0.125660
caption                     0.125660
licensedContent             0.125660
projection                  0.125660
liveActualStartTime       100.000000
liveScheduledStartTime    100.000000
concurrentViewers          99.901166
snapshot_date               0.000000
dtype: float64

In [ ]:
#Converting columns publishedAt and snapshot_date to datetime format
yt2 = pd.read_csv("youtube_dataset2", parse_dates=[''])